services:

  api:
    build: .
    container_name: pet-breed-api
    ports:
      - "8089:8089"

    environment:
      - YOLO_CONFIG_DIR=/tmp/Ultralytics

    env_file:
      - .env
      
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: pet-breed-postgres

    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: